name: Try secretes

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose Environment"
        required: true
        default: "development"
        type: choice
        options:
          - development
          - stage
          - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: development
      url: ${{ secrets.DEV_SERVER_URL }}
    if: inputs.environment == 'development'
    steps:
      - name: Move to server
        run: echo "${{ secrets.DEV_SERVER_URL }}"
