name: Try secretes

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose Environment"
        required: true
        default: "development"
        type: choice
        options:
          - development
          - stage
          - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: inputs.environment == 'development'
    environment:
      name: development
     # url: ${{ secrets.DEV_SERVER_URL }}
    steps:
      - name: Move to server
        run: echo "${{ inputs.environment }}"
