name: Try secretes

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Move to server
        run: echo "${{ secrets.SERVER_URL }}"
